name: local-mtls-
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
      tags:
        - mtls-nginx:v1
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - shared-data:/etc/nginx/vault:ro
    depends_on:
      vault:
        condition: service_healthy
  vault:
    build:
      context: ./vault
      dockerfile: vault.dockerfile
      tags:
        - mtls-vault:v1
    ports:
      - "127.0.0.1:8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    healthcheck:
      test: ls /vault/file/crl.crt
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - shared-data:/vault/file

volumes:
  shared-data: