name: local-mtls-
services:
  envoy:
    build:
      context: ./envoy
      dockerfile: envoy.dockerfile
      tags:
        - mtls-envoy:v1
    volumes:
      - shared-data:/etc/envoy/vault:ro
    ports:
      - "127.0.0.1:9901:9901"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8481:8481"
    depends_on:
      nginx:
        condition: service_started
      vault:
        condition: service_healthy
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
      tags:
        - mtls-nginx:v1
    ports:
      - "80"
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    volumes:
      - shared-data:/etc/nginx/vault:ro
    depends_on:
      vault:
        condition: service_healthy
  vault:
    build:
      context: ./vault
      dockerfile: vault.dockerfile
      tags:
        - mtls-vault:v1
    ports:
      - "127.0.0.1:8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    healthcheck:
      test: ls /vault/file/crl.pem
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - shared-data:/vault/file

volumes:
  shared-data: